### ISSUE TITLE
Driver issue

### ISSUE THREAD

**Issue by angegar** [forj-oss/forj-oss-infra#41]
@clarsonneur , Hi chris, hope your new life is going well.

When i run maintain.sh (forjj maintain production) i receive the error :

"Unable to maintain requester ressources of jenkins. Driver issue. The plugin as returned an error."

can this issue come  from a change in the ansible module ?

**Comment by angegar** [comment]
@clarsonneur , never mind, i found the root cause into our configuration files.

**Comment by clarsonneur** [comment]
Sure np!
